### ISSUE TITLE
The download of movie subtitlel doesn't work.

### ISSUE THREAD

**Issue by jim871** [ywk991112/pytorch-chatbot#23]
The download of movie subtitlel doesn't work. Can you add a new link? Thank you very much!

**Comment by jim871** [comment]
C:\Users\Cristian\Desktop\ai>python main.py -tr C:\Users\Cristian\Desktop\ai\save\training_data\intents\intents.json -l C:\Users\Cristian\Desktop\ai\save\training_data\intents\1_512\1_512 -lr 0.0001 -it 500 -b 64 -p 500 -s 1000
Start loading training data ...
Building encoder and decoder ...
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    run(args)
  File "main.py", line 48, in run
    n_layers, hidden_size, print_every, save_every, dropout, loadFilename=args.load)
  File "C:\Users\Cristian\Desktop\ai\train.py", line 176, in trainIters
    encoder.load_state_dict(checkpoint['en'])
TypeError: list indices must be integers or slices, not str
